### ISSUE TITLE
Dynamiccrossref issues

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hammer#230]
Dynamiccrossref (#226) seems to be erroring out.

In `defaults.yml`:

```
vlsi.submit:
  command: "local"
  settings: []

synthesis.submit:
  command: "${vlsi.submit.command}"
  command_meta: dynamicsubst
  # ---- this is broken ----
  settings: "vlsi.submit.settings"                                                                                                                                      
  settings_meta: dynamiccrossref
```

I'm getting:
```
ValueError: crossref (if used with lists) can only be used only with lists of strings
```
