### ISSUE TITLE
Make it easier to specify relative directory prefixes in extra_libraries

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#270]
Classic usecase:

`my_top.yml` and a folder `PLL/` containing `PLL.{lef,gds,lib}`.

```yaml
vlsi.technology.extra_libraries:
- prefix:
    prefix: "PLL"
    path: "" # <---- No good way to specify `PLL` relative to `my_top.yml`!!!
  library: {
    "lef file": "PLL/PLL.lef",
    "gds file": "PLL/PLL.gds",
    "nldm liberty file": "PLL/PLL.lib"
  }
```

**Comment by edwardcwang** [comment]
Current plan:
```yaml
vlsi.technology.extra_libraries_meta: deepsubst
vlsi.technology.extra_libraries:
- prefix:
  prefix: "PLL"
  path: "macros/pll" # <-- if this is abspath it can be detected and nothing happens
  path_substpath_meta: localpath
 library: {
  "lef file": "PLL/PLL.lef",
  "gds file": "PLL/PLL.gds",
  "nldm liberty file": "PLL/PLL.lib"
 }
- prefix:
  prefix: "LDO"
  path: "ldo" # <-- if this is abspath it can be detected and nothing happens
  path_substpath_meta: cwd
 library: {
  "lef file": "LDO/LDO.lef",
  "gds file": "LDO/LDO.gds",
  "nldm liberty file": "LDO/LDO.lib"
 }
- prefix:
  prefix: "ADC"
  path: "${technology.mytech.vendor_macros}/macros/adc" # general substitution
 library: {
  "lef file": "ADC/ADC.lef",
  "gds file": "ADC/ADC.gds",
  "nldm liberty file": "ADC/ADC.lib"
 }
```
