### ISSUE TITLE
Port parameter of clock constraints is not fully vendor-independent

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#280]
The syntax `pin:<path>` may not be vendor-independent: better to do just `<path>` and have each tool plugin translate.

```
vlsi.inputs.clocks:
- name: "digital_system_clock"
  generated: true
  port: "pin:MY_TOP/modA/modB/my_macro/clk_out"
  period: "100 ns"
  uncertainty: "1 ns"
```
