### ISSUE TITLE
Weird error in yaml snippet

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#334]
Reported by @dpgrubb13 

```
sim.rocketchip:
  riscv: "/tools/projects/riscv/install/latest"
  resources: "/tools/projects/user/hammer-footech60-template/rocket-chip/src/main/resources"

sim.inputs.compiler_opts: ["-I${sim.rocketchip.riscv}/include", "-std=c++11", "-Wl,-rpath,${sim.rocketchip.riscv}/lib"]
#sim.inputs.compiler_opts_meta: lazysubst
```
