### ISSUE TITLE
Expand sub-struct items for bumps by default in defaults.yml

### ISSUE THREAD

**Issue by edwardcwang** [ucb-bar/hammer#359]
Expand BumpsDefinition members by default to be consistent with other hammer settings. No functional change. May do this for #148 

```
# BumpsDefinition struct members
bumps:
  # - x (int) - number of bumps in the x dimension
  x: 0
  # - y (int) - number of bumps in the y dimension
  y: 0
```
