### ISSUE TITLE
Plugins with remote repos

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hammer#409]
This is a half-baked idea, but it might be nice to allow a user to point to a remote git repo (and/or other protocols like scp, https, etc.) rather than a locally-installed/submoduled plugin. I am thinking something like

```
vlsi.core.technology_plugin_location: git # could also be local, remote, scp, etc. (local is current behavior)
vlsi.core.technology_plugin_url: "git@github.com/ucb-bar/some_plugin.git"
```

This would make incorporating hammer into rebar a little less fragile, since we'd no longer need submodules for tech plugins (we can probably do the same for CAD plugins, too).

**Comment by edwardcwang** [comment]
Note that we already have:
```
vlsi.core:
  # Path(s) to out-of-tree hammer technology libraries.
  technology_path: ["${vlsi.builtins.hammer_vlsi_path}/technology"]
  technology_path_meta: subst
```

I think this is a very useful idea though it does require some attention to architect this feature correctly since it can be complex.
